# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fd53827c5003aec9984a2dcbe1dbca6e"
application_url = "https://lgd-usa-sync.mindhives.dev"
embedded = true
name = "lgd-jewelry-sync"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/products_update"
  topics = [ "products/update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_product_feeds,write_product_feeds,read_product_listings,write_product_listings,read_products,write_products,read_locations,read_inventory,write_inventory"

[auth]
redirect_urls = [ "https://lgd-usa-sync.mindhives.dev/auth/callback" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
